# Generated by Django 4.2.3 on 2023-07-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='people',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
